### ISSUE TITLE
Service 'words' failed to build

### ISSUE THREAD

**Issue by spara** [dockersamples/k8s-wordsmith-demo#1]
➜  k8s-wordsmith-demo git:(master) ✗ docker version
Client:
 Version:	18.03.0-ce-rc1
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	c160c73
 Built:	Thu Feb 22 02:34:03 2018
 OS/Arch:	darwin/amd64
 Experimental:	true
 Orchestrator:	kubernetes

Server:
 Engine:
  Version:	18.03.0-ce-rc1
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	c160c73
  Built:	Thu Feb 22 02:42:37 2018
  OS/Arch:	linux/amd64
  Experimental:	true

How to reproduce:

➜  k8s-wordsmith-demo git:(master) ✗ docker-compose build

Error:

Executing java-common-0.1-r0.trigger
OK: 81 MiB in 50 packages
rm: can't remove 'usr/lib/libtasn1.so.6.5.4': No such file or directory
ERROR: Service 'words' failed to build: The command '/bin/sh -c apk add --no-cache openjdk8-jre="8.151.12-r0" && rm usr/lib/libgif.so.7.0.0 usr/lib/libtasn1.so.6.5.4' returned a non-zero code: 1
➜  k8s-wordsmith-demo git:(master) ✗

**Comment by johnharris85** [comment]
Looks like `alpine:edge` bumped the version of `libtasn` to `6.5.5`. Should probably pin `alpine` to `3.7` (tested working) or update the `rm` line. Happy to PR whichever way you want to go @sixeyed.

**Comment by sixeyed** [comment]
Thanks for checking through @johnharris85. My preference is to pin the `FROM` image - PR much appreciated :)

**Comment by rnkhouse** [comment]
Changed `alpine:3.7` in my local copy. Still getting the same error.
