### ISSUE TITLE
errors during building 'web' image

### ISSUE THREAD

**Issue by GitHubDiom** [dockersamples/k8s-wordsmith-demo#17]
```
# command-line-arguments
/usr/local/go/pkg/tool/linux_arm64/link: running gcc failed: exec: "gcc": executable file not found in $PATH
```
Occurs when building this [webimage](https://github.com/dockersamples/k8s-wordsmith-demo/blob/f188cd6bdfdedf4290c001e0517767b0dd278689/web/Dockerfile) image

This seems to be another base image that needs to be changed.

**Comment by BretFisher** [comment]
Should be fixed, and now supports `arm64` and `arm/v7` as well.
