### ISSUE TITLE
unable to recognize "kube-deployment.yml": no matches for kind "Deployment" in version "apps/v1beta1"

### ISSUE THREAD

**Issue by blue-apple-technology** [dockersamples/k8s-wordsmith-demo#18]
unable to recognize "kube-deployment.yml": no matches for kind "Deployment" in version "apps/v1beta1"

**Comment by BretFisher** [comment]
Change to `apps/v1` and it should work on the latest Kubernetes version.

**Comment by BretFisher** [comment]
fixed in #11
