### ISSUE TITLE
Unable to display words, page crashes on refresh. 

### ISSUE THREAD

**Issue by sethmccombs** [dockersamples/k8s-wordsmith-demo#4]
I am able to get the kube yml to deploy, but when I navigate to localhost:8081, I get a page with the proper layout, but no words. Console error screenshot attached. If I refresh that page, it no longer connects. 

I'm running this on a local tectonic cluster. I've relaunched the cluster, deleted my docker images and reapplied the kubenetes yml. 

![screen shot 2018-05-11 at 2 18 12 pm](https://user-images.githubusercontent.com/5605413/39947693-b4c6f42e-5527-11e8-9e2d-af091808d924.png)

**Comment by sethmccombs** [comment]
Also seeing `WARNING: Some services (words) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.` when `docker-compose pull` is run

**Comment by ruiengana** [comment]
If you do a curl/wget diretly to backend api you always get the same noun, verb, or adjective result. It seems somewhere along the way the request is being cached or java code (JDBC) is ignoring random() function in SQL query.

**Comment by ManoMarks** [comment]
@sethmccombs I'm reviewing old issues. We're not able to reproduce this issue, so closing. Re-open if still an issue
